# SAST Workflow for the DevSecOps & Cloud Security course

name: snyk-security

on:
  workflow_call:
    secrets:
      SNYK_TOKEN:
        required: true

permissions:
  contents: read

jobs:
  checkov:
    name: Checkov scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run checkov scanner
        uses: bridgecrewio/checkov-action@master
        continue-on-error: true 
        with:
          directory: .
          framework: all
          quiet: true
          soft_fail: true
          download_external_modules: true
          output_format: sarif
  secrets-scanner:
    name: Scan for secrets using gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: gitleaks-action
        uses: zricethezav/gitleaks-action@master
        continue-on-error: true
  semgrep:
    name: 🐛 Semgrep Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    container:
      image: returntocorp/semgrep:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run semgrep security scanner
        continue-on-error: true
        run: |
          cat << 'EOF' | bash
              semgrep ci --config=auto --sarif --output=semgrep.sarif --max-target-bytes=2MB
              EXIT_CODE=$?
              if [ "$EXIT_CODE" = "0" ] || [ "$EXIT_CODE" = "1" ]
              then
                exit 0
              else
                exit $EXIT_CODE
              fi
          EOF
      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif 
  snyk:
    name: Snyk scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Run npm install before scanning
        run: npm install
      - name: Run Snyk
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true
